---
global:
  password: yuji
#  mobileid: 5u9032kjsajlas_tw.ezweb.ne.jp
  keywords:
     - ebith
     - えび
#   stopwords:
#     - tokuhirom31

plugin:
  - module: Component::IRCClient
    config:
      server: 127.0.0.1
      port: 6667
      nick: ebith
      desc: ebith
      username: ebith
      password: uup8y9hw
      incode: utf-8

  - module: Component::HTTPD
    config:
      port: 5678

  - module: IRCCommand::TiarraLog
  - module: MessageBodyFilter::Clickable
    config:
      pocket_hatena: 1

